FROM nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04

# ON LOCAL resolve problem realted to docker run
# distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
# curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
# curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
# sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
# sudo systemctl restart docker

# OPENCL
# https://linuxhandbook.com/setup-opencl-linux-docker/

# Immediate flush
ENV PYTHONUNBUFFERED TRUE

RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    build-essential \
    ca-certificates \
    g++ \
    python3-dev \
    python3-distutils \
    python3-venv \
    curl \
    xz-utils \
    clinfo \
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp \
    && curl -O https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py

# clinfo 0 platform fix
RUN mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

RUN ln -s /usr/local/cuda/lib64/libOpenCL.so.1 /usr/lib/libOpenCL.so

# for visibility of docker
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN python3 -m venv /home/prophet

ENV PATH "/home/prophet/bin:$PATH"

RUN python3 -m pip install --upgrade cmdstanpy[all] --no-cache-dir  && \
    python3 -c "import cmdstanpy; cmdstanpy.install_cmdstan()" && \
    # For passing prophet tests
    ln ./.cmdstan/cmdstan-2.28.2/stan/lib/stan_math/lib/tbb/libtbb.so.2 /usr/lib/libtbb.so.2

# Rebuild with stan opencl gpu
COPY local /root/.cmdstan/cmdstan-2.28.2/make/
RUN cd /root/.cmdstan/cmdstan-2.28.2/ && make build

COPY example.json example.py /home/prophet/
COPY ./prophet/python/ /home/prophet/python/
RUN cd /home/prophet/python && export STAN_BACKEND=CMDSTANPY && pip install .
