FROM ubuntu:20.04

ENV PYTHONUNBUFFERED TRUE

RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    build-essential \
    ca-certificates \
    g++ \
    python3-dev \
    python3-distutils \
    python3-venv \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp \
    && curl -O https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py

RUN python3 -m venv /home/prophet

ENV PATH "/home/prophet/bin:$PATH"

RUN python3 -m pip install --upgrade cmdstanpy[all] --no-cache-dir && \
    python3 -c "import cmdstanpy; cmdstanpy.install_cmdstan()"

COPY example.json example.py /home/prophet/
